# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9OSxNx3-8QcvAmS4gQ4bTI-r7-tpnED
"""

#teste salvar no Git ,py
print ("teste estensão py no git via Colab")